//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Msw.rc
//
#define rVersionInfo                    1
#define IDC_EDIT1                       3
#define IDOK2                           3
#define IDC_GROUP1                      4
#define IDOK3                           4
#define ID_EDIT                         4
#define IDC_BUTTON1                     5
#define IDC_LIST1                       5
#define ID_SETTINGS                     5
#define rMenuInPlace                    6
#define IDOK4                           6
#define ID_ADD                          6
#define IDOK5                           8
#define ID_REMOVE                       8
#define ID_CONNECT                      9
#define ID_CONNECT2                     10
#define ID_LOGIN                        10
#define rGrammar                        99
#define IDP_OLE_INIT_FAILED             100
#define rMainFrame                      101
#define rIcoMainFrame                   101
#define IDC_BUTTON2                     102
#define IDP_FAILED_TO_CREATE            102
#define IDD_MEMHOG_DIALOG               102
#define IDC_BUTTON3                     103
#define IDS_INVALID_MEASUREMENT         103
#define IDC_BUTTON4                     104
#define rIcoRightToLeft                 104
#define IDS_PLEASE_WAIT                 104
#define rIcoLeftToRight                 105
#define IDS_COMPLETE                    105
#define IDS_SAVE_UNSUPPORTED            106
#define IDS_CLOSE_TEXT                  107
#define IDS_RICHED_LOAD_FAIL            108
#define rBmpPclip                       108
#define rStrDefaultFont                 109
#define rBmpBmark                       109
#define IDS_TF_BUTTONS                  110
#define IDC_COMBO_ALIGNMENT             111
#define rStrControlPanelCaption         111
#define IDS_SAVE_FORMAT_TEXT            112
#define IDC_COMBO_SPACING               112
#define IDS_SAVE_FORMAT                 113
#define IDS_SAVING                      113
#define rBmpRightArrow                  113
#define rBmpRightArrowM                 114
#define IDS_CLIP_RTF                    114
#define rBmpLeftArrow                   115
#define IDS_FORMATTING                  115
#define rBmpLeftArrowM                  116
#define IDS_LEFT                        116
#define IDS_CENTER                      117
#define rDlgBookmarkName                118
#define IDS_RIGHT                       118
#define IDS_MEASUREMENT_RANGE           119
#define IDS_INVALID_NUMBER              120
#define IDS_INVALID_FONTSIZE            121
#define IDS_INCHES                      122
#define IDS_CENTIMETERS                 123
#define IDS_POINTS                      124
#define IDS_PICAS                       125
#define IDS_WORD6_WARNING               126
#define IDS_WORD6_WARNING_BUTTONS       127
#define rStrSingleSpace                 128
#define IDS_TEXT_DOC                    129
#define rMagicsType                     129
#define IDS_RICHTEXT_DOC                130
#define IDB_BITMAP_TT                   130
#define IDB_RULER_BLOCK                 131
#define rStrOneAndAHalfSpace            131
#define IDS_ALL_DOC                     132
#define IDB_RULER_BLOCKM                132
#define IDS_WINWORD6_DOC                133
#define IDB_RULER_DOWN                  133
#define IDS_WINWORD2_DOC                134
#define IDB_RULER_DOWNM                 134
#define rCurScroll                      134
#define IDB_RULER_TAB                   135
#define IDS_EXE_DOC                     135
#define rDlgVideoConfig                 135
#define IDB_RULER_TABM                  136
#define IDS_FILE_EXISTS                 136
#define IDB_RULER_UP                    137
#define IDS_MAPILOAD_FAILED             137
#define IDS_OEMTEXT_DOC                 137
#define IDB_RULER_UPM                   138
#define IDS_CLIP_TEXT                   138
#define rIcoNtsc                        138
#define IDB_FORMATBAR                   139
#define IDS_CLIP_FILENAME               139
#define rDlgScriptQueue                 139
#define rStrNoConverter                 139
#define rTbFormat                       139
#define IDR_MAINFRAME1                  140
#define rStrSpellerInit                 140
#define IDB_FORMATBAR_BIG               141
#define rStrDoubleSpace                 141
#define IDR_MAINFRAME_BIG               142
#define IDS_JUSTIFY                     142
#define IDR_MAINFRAME1_BIG              143
#define rDlgParaFormat                  143
#define IDS_NEW_STYLE                   143
#define rDlgGotoLine                    144
#define IDP_CONFIRM_DELETE              144
#define IDS_STRING145                   145
#define IDP_DUPLICATE_STYLE             145
#define IDP_BOOKMARK_NAME               146
#define IDS_DEFAULT_BOOKMARK_NAME       147
#define IDC_FONTSTYLE                   148
#define IDS_DT1                         149
#define rBmpBlip                        149
#define IDP_DUPLICATE_BOOKMARK          149
#define IDS_DT2                         150
#define IDS_MAX_BOOKMARKS               150
#define IDS_DT3                         151
#define rStrGotoBookmark                151
#define IDS_DT4                         152
#define rMenuTextPopup                  152
#define IDS_SET_PAPERCLIP               152
#define IDS_DT5                         153
#define rDlgSpellDialog                 153
#define IDS_SET_PAPERCLIP2              153
#define IDS_DEL_PAPERCLIP               153
#define IDS_DT6                         154
#define IDS_STRING154                   154
#define rStrPreferencesDlg              154
#define IDS_DT7                         155
#define IDS_STRING155                   155
#define rStrMissingConverter            155
#define IDS_DT8                         156
#define rStrConfirmClear                156
#define IDS_DT9                         157
#define rDlgAbout                       157
#define rStrScriptQName                 157
#define IDS_DT10                        158
#define rBmpIconBar                     158
#define rStrScriptQErt                  158
#define IDS_DT11                        159
#define rStrScriptQArt                  159
#define IDS_DT12                        160
#define rStrScriptsQueued               160
#define IDS_DT13                        161
#define IDS_STRING161                   161
#define rStrScriptsRunTime              161
#define rStrScriptBookmarksMenu         162
#define IDB_BITMAP_PRINTER              163
#define rStrInvalidCharacters           163
#define IDS_FINISHED_SEARCH             164
#define IDC_FONTNAME                    165
#define IDC_FONTSIZE                    166
#define IDS_TITLE_FORMATBAR             167
#define IDB_PRINTER                     167
#define IDB_FONTTYPE                    167
#define IDS_TITLE_TOOLBAR               168
#define IDS_INCH1_ABBREV                169
#define IDS_INCH2_ABBREV                170
#define IDS_INCH3_ABBREV                171
#define IDS_INCH4_ABBREV                172
#define rBmpCompanyLogo                 172
#define IDS_CM_ABBREV                   173
#define rBmpMswLogo                     173
#define IDS_POINT_ABBREV                174
#define IDS_PICA_ABBREV                 175
#define IDB_BITMAP1                     175
#define IDS_NOMORETABS                  176
#define rDlgScrollPrefs                 176
#define rDlgStyle                       177
#define IDS_MAPI_FAIL                   177
#define rListStyle                      178
#define IDS_ERRSPACE                    178
#define IDS_CANT_LOAD                   179
#define IDS_TOOMANYFILES                180
#define IDS_DIRFULL                     181
#define IDS_SHAREVIOLATION              182
#define IDS_TEXT_OPTIONS                183
#define IDS_RTF_OPTIONS                 184
#define IDS_WORD6_OPTIONS               185
#define IDS_OPTIONS                     186
#define IDS_WRITE_OPTIONS               187
#define IDS_EMBEDDED_OPTIONS            188
#define IDS_TEXT_DOCUMENT               189
#define IDS_RTF_DOCUMENT                190
#define IDS_WORD6_DOCUMENT              191
#define IDS_WRITEPROTECT                192
#define IDS_TITLE_ICONBAR               193
#define rTbIconBig                      193
#define IDS_STRING194                   194
#define rStrExpired                     194
#define rStrWillExpire                  195
#define rDlgScroll                      196
#define rStrCancelBtn                   196
#define rDisabled                       197
#define rMenuDisabled                   197
#define rStrTimer                       197
#define IDS_URICHTEXT_DOC               198
#define rDlgGeneralPrefs                198
#define IDS_UTEXT_DOC                   199
#define IDB_BITMAP2                     200
#define rBmpCheckboxes                  200
#define rStrFinishedReplaceAll          200
#define IDP_NO_STYLE_NAME               201
#define rStrExpiredReg                  202
#define rBmpBackground                  203
#define IDI_ICON1                       203
#define rIcoBookmark                    203
#define rStrRulerLeftScroll             203
#define rBmpFont                        204
#define rIcoPaperclip                   204
#define rStrRulerRightScroll            204
#define rIcoCueBar0                     205
#define rStrRulerFirstLine              205
#define rIcoCueBar1                     206
#define rStrRulerHang                   206
#define rIcoCueBar2                     207
#define rMenuSize                       207
#define rStrRulerLeft                   207
#define rIcoCueBar3                     208
#define rMenuFormat                     208
#define rStrRulerRight                  208
#define rIcoCueBar4                     209
#define rDlgOtherSize                   209
#define rStrRulerRight2                 209
#define rStrRulerTabs                   209
#define rIcoCueBarWhite0                210
#define rStrAddStyle                    210
#define rIcoCueBarWhite1                211
#define rDlgUnregisteredVersion         211
#define rStrNotOnline                   211
#define rIcoCueBarWhite2                212
#define rDlgRegister                    212
#define rStrAddSlave                    212
#define rIcoCueBarWhite3                213
#define IDR_MENU1                       213
#define rStrConnStatus                  213
#define rIcoCueBarWhite4                214
#define rStrUnconnStatus                214
#define rIcoCueBar0Alt                  215
#define rBmpCueBar1                     215
#define IDS_STRING215                   215
#define rStrEditConnSlave               215
#define rIcoCueBar1Alt                  216
#define rBmpCueBar0                     216
#define rStrConnStatus0                 216
#define rIcoCueBar2Alt                  217
#define rBmpCueBar2                     217
#define rStrUnconnStatus0               217
#define rIcoCueBar3Alt                  218
#define rBmpCueBar3                     218
#define rStrConnect                     218
#define rIcoCueBar4Alt                  219
#define IDB_BITMAP3                     219
#define rBmpCueBar4                     219
#define rStrDisconnect                  219
#define rStrToolBarCaption              220
#define rTbMain                         220
#define rStrFormatBarCaption            221
#define rStrWarnLink                    222
#define IDB_BITMAP4                     223
#define rStrCloseApps                   223
#define rDlgRemote                      224
#define rStrCloseApps2                  224
#define rDlgAddSlave                    225
#define IDS_STRING225                   225
#define rStrInitProtection              225
#define rStrStyle                       226
#define rBmpDemo                        226
#define rBmpCompanyLogo1                227
#define rScrollAccelerators             227
#define rStrBtnLogout                   227
#define rStrBtnLogin                    228
#define rBmpFind                        260
#define rDlgFindCont                    513
#define rDlgReplaceCount                516
#define IDC_EDIT_LEFT                   1000
#define rCtlButtonDefaultFont           1000
#define IDC_TOTAL_PHYSICAL              1000
#define IDC_EDIT_RIGHT                  1001
#define IDC_TEXT1                       1001
#define IDC_REMAINING                   1001
#define IDC_EDIT_FIRST_LINE             1002
#define IDC_TEXT2                       1002
#define IDC_ALLOCATE                    1002
#define IDC_TEXT3                       1003
#define IDC_STATUS                      1003
#define IDC_TEXT4                       1004
#define IDC_VREMAINING                  1004
#define IDC_BUTTON_SET                  1005
#define IDC_EDIT_BM                     1005
#define IDC_BUTTON_CLEAR                1006
#define IDC_EDIT_LM                     1006
#define IDC_BUTTON_CLEARALL             1007
#define IDC_EDIT_RM                     1007
#define rCtlVcColor                     1007
#define rCtlBkMkName                    1008
#define rCtlGotoLine                    1008
#define rCtlPrefClearPc                 1008
#define rCtlVcInverse                   1008
#define rCtlOtherSize                   1009
#define rCtlPrefSync                    1009
#define rCtlVcShowSpeed                 1009
#define rCtlPrefPrintCue                1010
#define rCtlVcShowTimer                 1010
#define IDC_COMBO_WRAP                  1011
#define rCtlVcShowDividers              1011
#define IDC_COMBO_UNITS                 1012
#define rCtlVcShowPos                   1012
#define IDC_EDIT2                       1012
#define rCtlVcMirror                    1013
#define rCtlVcLoop                      1014
#define rCtlVcLink                      1015
#define IDC_EDIT_TM                     1016
#define rCtlErtCps                      1016
#define IDC_TEXT_ALIGNMENT              1017
#define IDC_LISTDIALOG_LIST             1018
#define IDC_TEXT_SPACING                1018
#define rCtrlModules                    1018
#define IDC_COMBO1                      1019
#define rCtlPrefsDefFontLang            1019
#define rCtlPort                        1019
#define IDC_TEXT_WRAP                   1020
#define rCtlBaud                        1020
#define rCtlBaudRate                    1020
#define IDC_TEXT_UNITS                  1021
#define rCtlByteSize                    1021
#define IDC_BOX                         1022
#define rCtlPrefLButton                 1022
#define rCtlParity                      1022
#define IDC_BIGICON                     1023
#define rCtlPrefRButton                 1023
#define rIcoAppBig                      1023
#define rCtlStopBits                    1023
#define IDC_UNITS_IN                    1024
#define IDC_UNITS_CM                    1025
#define IDC_UNITS_PT                    1026
#define IDC_UNITS_PI                    1027
#define IDC_CHECK_TOOLBAR               1028
#define IDC_CHECK_FORMATBAR             1029
#define IDC_WORDSEL                     1029
#define rCtlPrefResetTimer              1029
#define IDC_CHECK_RULERBAR              1030
#define rCtlPrefManualTimer             1030
#define IDC_CHECK_STATUSBAR             1031
#define IDC_BOXT                        1032
#define rCtlVersion                     1033
#define rCtlErtDefault                  1034
#define rCtlWarning                     1034
#define rCtlCompany                     1035
#define rCtlReplaceCount                1036
#define rCtlMsw                         1036
#define rCtlVersion2                    1036
#define rCtlGotoRange                   1037
#define rCtlStatic99                    1038
#define rCtlPrefSensitivity2            1039
#define rCtlRichEdit                    1039
#define rCtlFindFormat                  1039
#define rCtlPrefSensitivity             1040
#define rCtrlList                       1040
#define rCtlPrefSensitivity3            1041
#define rCtlVcMirrorIcon                1041
#define rCtrlStatus                     1041
#define rCtlPrefSensitivity4            1042
#define rCtrlStatus2                    1042
#define rCtlUseFindFormat               1042
#define rCtlPrefRevSpeed                1043
#define rCtlUseReplaceFormat            1043
#define rCtrlOtherSize                  1043
#define rCtlVtSpell1                    1044
#define rCtlPrefRevSpeed2               1044
#define rCtlFindFormat2                 1044
#define rCtlReplaceFormat               1044
#define rCtlPrefInverseEditMode         1044
#define rCtlFrameTxt                    1045
#define IDC_COMPUTER_ID                 1045
#define rCtlConnection                  1047
#define rCtlMe                          1048
#define rCtlMe2                         1049
#define rCtlSlaves                      1050
#define rCtlRegNumber                   1051
#define rCtlConnection0                 1051
#define rCtlRegNumber2                  1052
#define rCtlRemoteName                  1052
#define rCtlCcEnable                    1052
#define rCmdToggleInverseEdit           1099
#define rCmdViewNtsc                    1100
#define rCmdViewQueue                   1101
#define rCmdToggleInverseOut            1102
#define rCmdToggleScrollMode            1103
#define rCmdViewUpdate                  1104
#define rCmdViewConfig                  1105
#define rStrEmptyReg                    1106
#define rStrRegExpired                  1107
#define rStrRegPriorVersion             1108
#define rStrInvalidReg                  1109
#define rStrRegNameEmpty                1110
#define rCmdStylePlain                  2000
#define rCmdStyleBold                   2001
#define rCmdStyleItalics                2002
#define rCmdStyleUnderline              2003
#define rCmdFontSelect                  2200
#define rCmdSize12                      2312
#define rCmdSize18                      2318
#define rCmdSize24                      2324
#define rCmdSize36                      2336
#define rCmdSize40                      2340
#define rCmdSize48                      2348
#define rCmdSize64                      2364
#define rCmdSize72                      2372
#define rCmdSize96                      2396
#define rCmdSizeLarger                  2397
#define rCmdSizeSmaller                 2398
#define rCmdSizeOther                   2399
#define rCmdColorBlack                  3000
#define rCmdColorRed                    3001
#define rCmdColorPink                   3002
#define rCmdColorGreen                  3003
#define rCmdColorYellow                 3004
#define rCmdColorBlue                   3005
#define rCmdColorTeal                   3006
#define rDlgFindReplace                 28683
#define rDlgEval                        28684
#define rDlgAboutReg                    28685
#define rDlgCaptionsConfig              28686
#define rCmdInsertDate                  32778
#define rCmdFormatPara                  32780
#define rCmdColor0                      32782
#define rCmdColor1                      32783
#define rCmdColor2                      32784
#define rCmdColor3                      32785
#define rCmdColor4                      32786
#define rCmdColor5                      32787
#define rCmdColor6                      32788
#define rCmdColor7                      32789
#define rCmdColor8                      32790
#define rCmdColor9                      32791
#define rCmdColor10                     32792
#define rCmdColor11                     32793
#define rCmdColor12                     32794
#define rCmdColor13                     32795
#define rCmdColor14                     32796
#define rCmdColor15                     32797
#define rCmdColor16                     32798
#define rCmdColor17                     32799
#define rCmdColor18                     32800
#define rCmdColor19                     32801
#define ID_CHAR_BOLD                    32802
#define ID_CHAR_ITALIC                  32803
#define ID_CHAR_COLOR                   32804
#define ID_CHAR_UNDERLINE               32805
#define ID_PARA_LEFT                    32806
#define ID_PARA_CENTER                  32807
#define ID_PARA_RIGHT                   32808
#define ID_OLE_VERB_POPUP               32811
#define rCmdTogglePaperclip             32815
#define rCmdViewRuler                   32816
#define rCmdListen                      32817
#define rCmdVoiceTraining               32818
#define rCmdMicSetup                    32835
#define rCmdFormatBullets               32837
#define rCmdFormatTabs                  32839
#define rCmdBookmarks                   32899
#define rCmdLoop                        32901
#define rCmdOut                         32902
#define rCmdLink                        32903
#define ID_UTILITIES_AUTOCHECKOPTIONS   32933
#define ID_FORMAT_BULLETS               32942
#define ID_FORMAT_STYLES                32943
#define ID_FORMAT_SEQ                   32944
#define ID_VIEW_SCRIPTQUEUE             32945
#define ID_VIEW_SHOWINVISIBLES          32946
#define ID_HELP_MAGICSCROLLONTHEWEB     32947
#define rCmdHelpWeb                     32948
#define ID_BOOKMARKS_SETBOOKMARK        32950
#define ID_BOOKMARKS_GOTOBOOKMARK       32952
#define rCmdNextBkmk                    32955
#define rCmdPrevBkmk                    32956
#define rCmdToggleTimer                 32963
#define rCmdFormatFontBtn               32967
#define ID_SIZE_12                      32968
#define ID_SIZE_18                      32969
#define ID_SIZE_24                      32970
#define ID_SIZE_36                      32971
#define ID_SIZE_40                      32972
#define ID_SIZE_48                      32973
#define ID_SIZE_64                      32974
#define ID_SIZE_72                      32975
#define ID_SIZE_96                      32976
#define ID_SIZE_LARGER                  32977
#define ID_SIZE_SMALLER                 32978
#define ID_SIZE_OTHER                   32979
#define ID_STYLE_PLAIN                  32980
#define ID_STYLE_BOLD                   32981
#define ID_STYLE_ITALICS                32982
#define ID_STYLE_UNDERLINE              32983
#define ID_STYLE_LEFT                   32984
#define ID_STYLE_CENTER                 32985
#define ID_STYLE_RIGHT                  32986
#define ID_STYLE_1SPACE                 32987
#define ID_STYLE_15SPACE                32988
#define ID_STYLE_2SPACE                 32989
#define ID_BUTTON33003                  33003
#define ID_TIMER                        33003
#define ID_HELP_REGISTERMAGICSCROLL     33005
#define rCmdHelpRegisterMsw             33006
#define ID_INSERT_BULLET                33007
#define ID_FORMAT_PARAGRAPH             33008
#define ID_PEN_SPACE                    33009
#define ID_PEN_TAB                      33010
#define ID_PEN_NEWLINE                  33011
#define ID_PEN_LENS                     33012
#define rCmdTimerToArt                  33013
#define rCmdScrollLineUp                33015
#define rCmdScrollLineDown              33016
#define ID_BUTTON33020                  33020
#define ID_BUTTON33021                  33021
#define ID_BUTTON33022                  33022
#define ID_BUTTON33023                  33023
#define ID_BUTTON33024                  33024
#define ID_BUTTON33025                  33025
#define ID_BUTTON33026                  33026
#define ID_BUTTON33027                  33027
#define ID_BUTTON33028                  33028
#define ID_BUTTON33029                  33029
#define ID_ACCELERATOR33030             33030
#define rCmdBetaFeedback                33032
#define ID_TOOLS_REMOTESCROLL           33033
#define ID_BUTTON33054                  33054
#define ID_TOOLS_REMOTEINSTALLATIONS    33055
#define rCmdRemote                      33056
#define rCmdStyleCenter                 40008
#define rCmdStyleLeft                   40009
#define rCmdStyleRight                  40010
#define rCmdEditRight                   40011
#define rCmdSetBkMk1                    40015
#define rCmdClearBkMks                  40041
#define rCmdClearPclips                 40042
#define rCmdTimerReset                  40065
#define rCmdEditPrefs                   40070
#define rCmdNextPclip                   40072
#define rCmdPrevPclip                   40073
#define rCmdEditTof                     40074
#define rCmdEditEof                     40075
#define rCmdEditBol                     40076
#define rCmdEditEol                     40077
#define rCmdViewShowLineNum             40081
#define rCmdViewShowInvis               40082
#define rCmdGotoLine                    40083
#define rCmdCheckSpelling               40085
#define rCmdSpellerOptions              40087
#define rCmdAutoCorrectOptions          40088
#define rCmdViewIconBar                 40092
#define rCmdGotoBkMk1                   40100
#define rCmdStyle1                      41100
#define rCmdFileSaveCopyAs              57599
#define rCmdFileNew                     57600
#define rCmdFileOpen                    57601
#define rCmdFileClose                   57602
#define rCmdFileSave                    57603
#define rCmdFileSaveAs                  57604
#define rCmdFilePageSetup               57605
#define rCmdFilePrintSetup              57606
#define rCmdFilePrint                   57607
#define rCmdPrintDirect                 57608
#define rCmdFilePrintPreview            57609
#define rCmdFileSend                    57612
#define rCmdEditClear                   57632
#define rCmdEditCopy                    57634
#define rCmdEditCut                     57635
#define rCmdEditPaste                   57637
#define rCmdEditPasteSpecial            57639
#define rCmdEditFindNext                57640
#define rCmdEditFind                    57641
#define rCmdEditSelectAll               57642
#define rCmdEditUndo                    57643
#define rCmdWindowArrange               57649
#define rCmdWindowCascade               57650
#define rCmdWindowTileHoriz             57651
#define rCmdAppAbout                    57664
#define rCmdAppExit                     57665
#define rCmdHelpTopics                  0xE142
#define rCmdContextHelp                 57669
#define rCmdNextPane                    57680
#define rCmdPrevPane                    57681
#define rCmdFormatFont                  57696
#define rCmdInsertOle                   57856
#define rCmdEditLinks                   57857
#define rCmdEditObjectProperties        57860
#define rCmdViewToolbar                 59392
#define rCmdViewStatusBar               59393
#define rCmdViewFormatbar               59396
#define rCmdCuePointer0                 59400
#define rCmdCuePointer9                 59409

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         33057
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
